rules:
  - name: "sync-master-to-demo"
    mode: in-sync
    source_branch: master
    destination_rules:
    - name: "demo"
      exclude dir:
      - ".pipeline"
      exclude_file: 
      - ".gitignore"